import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title> Data Visualization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.heroContent}>
        <p className={styles.WebsiteName}>📊 DataLens</p>
        <p className={styles.appDesc}>Explore, analyze, and understand your data like never before.</p>
          <Link href="/auth">Sign Up</Link>
        </main>
      </div>
    </>
  );
}
